### PR TITLE
ENH: Rewrite kdp_brute module in Cython

### PR DESCRIPTION
**Pull request by jjhelmus**
Replace the Fortran kdp_brute module with a version written in Cython.

The fill_psidp and lowpass_maesaka_cost subroutines were not converted to
Cython as they are not used in the kdp_proc modules.

### CODE REVIEW

**Comment by kirknorth** [comment]
@jjhelmus thanks for the Cython extension! You mentioned that there was no significant change in processing time. Do you have any numbers you could share, e.g., for x number of sweeps doing y number of iterations it took z seconds.

**Comment by jjhelmus** [comment]
Some timing number from a small toy example that I was using for testing:

``` Python
import numpy as np
import pyart
from pyart.retrieve import kdp_proc

radar = pyart.io.read('KVNX20110520_101906_V06')
radar = radar.extract_sweeps([0])
for field in radar.fields.keys():
    radar.fields[field]['data'][:, 292:] = np.ma.masked

kdp, phidpf, phidpb = kdp_proc.kdp_maesaka(radar)
```

Using the Fortran extension the last line takes ~14.5 seconds to execute, with the Cython extension the last line takes ~13.5 seconds (both measured with IPython %timeit magic).  This is to process a single sweep with 720 rays and 292 non-masked gates per ray using the default parameter.

**Comment by kirknorth** [comment]
@jjhelmus seems reasonable then, the default number of iterations (`maxiter`) is 50. When I used the first 5 sweeps from a KVNX volume it took a total of 45-50 sec for 50 iterations, so roughly 10 sec for one sweep.

**Comment by kirknorth** [comment]
@jjhelmus I have not forgotten about this. One question is should we respect the row-major order of C and have the inner loops accessing the right-most index so we don't lose performance?

``` python
for ray in range(nr):
   for gate in range(ng):
      d2kdr2[ray, gate] = ...  
```

**Comment by jjhelmus** [comment]
Yes, changing so that the inner most loop is over the right-most index is a better idea since we've switched to a row-majored ordered language.  With the big pipelines and fancy optimization schemes in today's processors and compilers I would not expect to see a huge impact on performance but it can't hurt.  

I'll add another commit shortly to this PR to change the loop order.

**Comment by kirknorth** [comment]
Great, thanks. What is the best way for me to test your changes and possibly edit them before merging, since merging will then send it up the pipeline to the original PR.

**Comment by jjhelmus** [comment]
You can check out my [pull request locally](https://help.github.com/articles/checking-out-pull-requests-locally/) and review and possibly add additional commit before merging it into your branch.  I've used that method a number of times.

**Pull request merged**
